DJANGO/해쉬태그/hastag+follow+like/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/profile/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

DJANGO/해쉬태그/hastag+follow+like/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/',
         views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name="likes"),
    path('<int:hash_pk>/hashtag/', views.hashtag, name="hashtag"),
]

DJANGO/해쉬태그/hastag+follow+like/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

DJANGO/해쉬태그/hastag+follow+like/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    following = models.ManyToManyField('self', symmetrical=False, related_name="follower")

DJANGO/해쉬태그/hastag+follow+like/movies/models.py
from django.db import models
from django.conf import settings

class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content


class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

DJANGO/해쉬태그/hastag+follow+like/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

DJANGO/해쉬태그/hastag+follow+like/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    PasswordChangeForm
)
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import get_user_model
# Create your views here.


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('movies:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('movies:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    # 전체유저 네임 중에서 내가 클린한 유저의 이름이랑 같은 데이터를 가져온다.
    person = get_user_model().objects.get(username = username)
    context = {
        'person' : person
    }
    return render(request, 'accounts/profile.html', context)
        

def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        if request.user != person:  # 지금 로그인한 사람과 같지 않다면
            if person.follower.filter(pk=request.user.pk).exists():
                person.follower.remove(request.user)
            else:
                person.follower.add(request.user)
        
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

DJANGO/해쉬태그/hastag+follow+like/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-sm">
  </form>
{% endblock content %}

DJANGO/해쉬태그/hastag+follow+like/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-sm">
  </form>
{% endblock content %}

DJANGO/해쉬태그/hastag+follow+like/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} person인 이유는 {% endcomment %}
    <h1>{{person}}님의 프로필</h1>
    <div>
        Following : {{person.following.all|length}}명 | Follower : {{person.follower.all|length}}명
        
    </div>
    {% comment %} {% if request.user == person.username %} {% endcomment %}
    {% if user != person %}
    
    <form action="{% url 'accounts:follow' person.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in person.follower.all %}
            <button class="btn btn-danger">Unfollow</button>
        {% else %}
            <button class="btn btn-primary">Follow</button>
        {% endif %}
    {% endif %}

    </form>
    <hr>


    <h2>{{person}}'s 게시글</h2>
    {% for movie in person.movie_set.all %}
        <div>{{movie.title}}</div>
    {% endfor %}
    <hr>

    <h2>{{person}}'s 댓글</h2>
    {% for comment in person.comment_set.all %}
        <div>{{comment.content}}</div>
    {% endfor %}
    <hr>
    <a href="{% url 'movies:index' %}">[BACK]</a>

{% endblock content %}

DJANGO/해쉬태그/hastag+follow+like/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>회원 가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-sm">
  </form>
{% endblock content %}

DJANGO/해쉬태그/hastag+follow+like/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>회원 정보 수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-sm">
  </form>
{% endblock content %}