DJANGO/0322민석쌤과함께/민석썜/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name="signup"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('change_password/', views.change_password, name="change_password"),
]

DJANGO/0322민석쌤과함께/민석썜/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# 변경하기 쉽게 custom으로 만든다.
class User(AbstractUser):
    pass
    # 등급 등 유저의 추가적인 속성을 기록할 수 있음

DJANGO/0322민석쌤과함께/민석썜/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name")

DJANGO/0322민석쌤과함께/민석썜/accounts/views.py
from django.shortcuts import render, redirect
# 로그인 정보를 입력할 때 필요한 폼가져오기
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm
# Create your views here.
def login(request):

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("articles:index")
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    form = AuthenticationForm()
    context = {"form" : form}
    auth_logout(request)
    # return redirect("articles:index")
    return render(request, "accounts/babo.html", context)

def signup(request):

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("articles:index")

    else:
        form = CustomUserCreationForm()
    context = {
        "form":form
    }
    return render(request, "accounts/signup.html", context)



def delete(request):
    request.user.delete()
    auth_logout(request)    # 로그아웃해주기
    return redirect("articles:index")


def update(request):
    if request.method =="POST":
        form = CustomUserChangeForm(data=request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect("articles:index")

    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form":form}
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        # 변경시 로그인 유지
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form" : form
    }
    
    return render(request, "accounts/password.html", context)

DJANGO/0322민석쌤과함께/민석썜/accounts/templates/accounts/babo.html
{% extends 'base.html' %}


{% block content %}

    <h1>잘가 {{user}}</h1>

{% endblock content %}

DJANGO/0322민석쌤과함께/민석썜/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>LOGIN</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="로그인", class="btn btn-warning">
    </form>
    <a href="{% url 'articles:index' %}">처음화면으로</a>
{% endblock content %}

DJANGO/0322민석쌤과함께/민석썜/accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% block content %}
<h1>PASSWORD CHANGE</h1>
<hr>

<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="비밀번호 변경하기">
</form>

<a href="{% url 'articles:index' %}" class="btn btn-warning">홈 화면 가기</a>

{% endblock content %}

DJANGO/0322민석쌤과함께/민석썜/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>SIGNUP</h1>
<hr>

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
</form>

<a href="{% url 'articles:index' %}">홈 화면 가기</a>

{% endblock content %}

DJANGO/0322민석쌤과함께/민석썜/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<hr>

<form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정하기">
</form>

<a href="{% url 'articles:index' %}">홈 화면 가기</a>

{% endblock content %}