DJANGO/04_pjt/mypjt/movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

DJANGO/04_pjt/mypjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.CharField(max_length=50)
    description = models.TextField()
    actor_image = models.ImageField(blank=True)

DJANGO/04_pjt/mypjt/movies/forms.py
from django import forms
from .models import Movie

class MoviesForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = "__all__"

    release_date = forms.DateTimeField(widget=forms.NumberInput(attrs={'type': 'date'}),)
    score = forms.FloatField(widget=forms.NumberInput(attrs={'step':0.5, 'max':5, 'min':0}))
    genre = forms.CharField(widget = forms.Select(choices=[('comedy','comedy'),('thriller','thriller'),('romance','romance')]))

DJANGO/04_pjt/mypjt/movies/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MoviesForm
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        "movies" : movies
    }
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == "POST":    # create.html에서 submit을 눌러서 POST로 데이터가 들어오면
        form = MoviesForm(request.POST, request.FILES) # POST로 들어온 값과 FILES로 들어온 값을 form에 담아서
        if form.is_valid(): # 유효성을 검사하고
            movie = form.save() # movie에 저장한다.
            return redirect("movies:detail", movie.pk)  # 위의 movie로 정의한 값에서 pk값을 넣어 urls.py의 detail로 보낸다.
    else:   # index.html의 a테그 안에서 create로 이동할 때 get데이터 전송
        form = MoviesForm()
    context = {"form":form}
    return render(request, "movies/create.html", context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {"movie" : movie}
    return render(request, 'movies/detail.html', context)

def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == "POST":   # update.html에서 보냔 POST 데이터가 들어오면
        form = MoviesForm(request.POST, request.FILES, instance=movie)    # POST값, 이미지파일, 기존 request에서 수정 순서대로 인자 생성
        if form.is_valid(): # 유효성 체크
            form.save() # 저장
            return redirect("movies:detail", movie.pk)
    else:
        form = MoviesForm(instance=movie)   # 수정할 떄는 기존 데이터를 가지고 form에 넣어서 수정한다
    context = {"form":form,
               "movie":movie} # movie의 pk값을 보내줘야하기 때문에 movie값도 context에 넣어준다
    return render(request, "movies/update.html", context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect("movies:index")   # 누구를 지울지 pk가 없어도 되기 때문에 article.pk를 명시할 필요가 없음

DJANGO/04_pjt/mypjt/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>CREATE</h1>
    <hr>
    <form action="{% url 'movies:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

DJANGO/04_pjt/mypjt/movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block content %}
    <h1>DETAIL</h1>
    <hr>
    {{movie.title}}
    <br>
    <p>Audience : {{movie.audience}}</p>
    <p>Realease Dates : {{movie.release_date}}</p>
    <p>Genre : {{movie.genre}}</p>
    <p>Score : {{movie.score}}</p>
    <p>Poster URL : {{movie.poster_url}}</p>
    <p>actor : </p>

    {% if movie.actor_image %} 
        <img src="{{movie.actor_image.url}}" alt="">    
    {% endif %}
    
    <p>{{movie.description}}</p>
    <br>
    <div class="container d-flex ms-0 ps-0">
        <a href="{% url 'movies:update' movie.pk %}" class="btn btn-success border-dark">UPDATE</a>
        <form action="{% url 'movies:delete' movie.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE" class="btn btn-warning border-dark">
        </form>
        
    </div>
    <a href="{% url 'movies:index' %}" class="btn btn-primary border-dark">BACK</a>
{% endblock content %}

DJANGO/04_pjt/mypjt/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>INDEX</h1>
    <a href="{% url 'movies:create' %}">CREATE</a>  
    <hr>
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a><br>
        {{movie.score}}
        <hr>
    {% endfor %}
    
{% endblock content %}

DJANGO/04_pjt/mypjt/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>UPDATE</h1>
    <hr>
    
    <form action="{% url 'movies:update' movie.pk%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <input type="reset" value="Reset">
        <input type="submit" value="Submit">
    </form>
    
    <hr>
    <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock content %}