JS/0426_with django/댓글수정/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

JS/0426_with django/댓글수정/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comments_update, name='comments_update'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

JS/0426_with django/댓글수정/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

JS/0426_with django/댓글수정/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

JS/0426_with django/댓글수정/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        # fields = '__all__'
        fields = ('title', 'content',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('article', 'user',)

JS/0426_with django/댓글수정/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# 2. 두번째 방법 파이썬에서 json을 파싱해서 읽을수 있도록 처리
import json

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.order_by('-pk')
    
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@require_safe
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


# @login_required
@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user.is_authenticated:
        if request.user == article.user: 
            article.delete()
            return redirect('articles:index')
    return redirect('articles:detail', article.pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)

        # request.body 안의 데이터 json 데이터 뽑아서 처리
        json_data = json.loads(request.body)
        comment_form = CommentForm(json_data)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        context = {
            "articlePk" : article.pk, "commentPk" : comment.pk
        }
        return JsonResponse(context,status=200)
    return redirect('accounts:login')


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)

@require_POST
def comments_update(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment_form = CommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment_form.save()
            context = {
                "articlePk": article_pk,
                "commentPk" : comment_pk
            }
            return JsonResponse(context, status=200)
    return redirect("accounts:login") 


@require_POST
def likes(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            liked = False
        else:
            article.like_users.add(request.user)
            liked = True
        context = {
            'liked': liked,
            'count': article.like_users.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:login')

JS/0426_with django/댓글수정/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="작성">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

JS/0426_with django/댓글수정/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>DETAIL</h2>
  <h3>{{ article.pk }} 번째 글</h3>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성시각 : {{ article.created_at }}</p>
  <p>수정시각 : {{ article.updated_at }}</p>
  <hr>
  {% if user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE">
    </form>
  {% endif %}
  <a href="{% url 'articles:index' %}">[back]</a>
  <hr>
  <h4>댓글 목록</h4>
  <ul id="comment-list">
    {% for comment in comments %}
      <li data-comment-id={{comment.pk}}>
        {{ comment.user }} - {{ comment.content }}
        {% if user == comment.user %}
          <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>
          <button class="update-btn">UPDATE</button>
        {% endif %}
      </li>
    {% empty %}
      <p>댓글이 없어요..</p>
    {% endfor %}
  </ul>

  <hr>
  {% if request.user.is_authenticated %}
    <form id="comment-form">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#comment-form')
    const input = document.querySelector('[name=content]')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    const updateBtns = document.querySelectorAll(".update-btn")

    const updateFunction = function(event) {
      const comment_li = event.target.closest("li")
      
      console.log(comment_li.dataset.commentId)
      // li 태그의 innerHTML 을 바꿔서 INPUT태그와 BUTTON 만들기
      const input = document.createElement("input")
      const button1 = document.createElement("button")
      button1.innerText = "update"
      comment_li.append(input)
      comment_li.append(button1)

      button1.addEventListener("click" , e => {
        let data = new FormData()
        data.append("content" , input.value)

        axios({
          method : "post",
          url : `http://127.0.0.1:8000/articles/{{article.pk}}/comments/${comment_li.dataset.commentId}/update/`,
          data,
          headers : {
            "X-CSRFToken" : csrftoken
          }
        }).then((response) => {
          // 댓글 수정 요청 성공시 댓글의 내용도 새로 업데이트 
          // li태그의 innerHTML 을 바꿔주면 된다
          const {articlePk, commentPk} = response.data
          comment_li.innerHTML = `
          {{ request.user.username }} - ${input.value}
          <form action="/articles/${articlePk}/comments/${commentPk}/delete/" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>
          `
          comment_li.append(event.target)
          input.value = ""
        })
      })
    }

    updateBtns.forEach((btn) => {
      btn.addEventListener("click", updateFunction)
    })

    form.addEventListener('submit', function (event) {
      event.preventDefault()
	    // 이곳에 코드를 작성하세요
      const content = input.value

      const baseURL = "http://127.0.0.1:8000/"
      // 1. 첫번째 방법 데이터를 보낼때 formdata 형식으로 보내주기
      const data = new FormData()
      data.append("content", content)

      axios({
        method: "post",
        baseURL,
        url: `articles/{{article.pk}}/comments/`,
        headers : {
          "X-CSRFToken" : csrftoken
        },
        data : {
          "content" : content
        }
      }).then(response => {
        const {articlePk, commentPk} = response.data
        const ul = document.querySelector("#comment-list")
        const li = document.createElement("li")
        li.dataset.commentId = commentPk
        li.innerHTML = `
        {{ request.user.username }} - ${content}
        <form action="/articles/${articlePk}/comments/${commentPk}/delete/" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
        `
        const btn = document.createElement("button")
        btn.innerText = "UPDATE"
        btn.classList.add(".update-btn")
        btn.addEventListener("click", updateFunction)
        li.append(btn)

        ul.append(li)
        input.value = ""
      })
    })

  </script>
{% endblock script %}

JS/0426_with django/댓글수정/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">[CREATE]</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <hr>
  {% for article in articles %}
    <p>작성자 : 
      <a href="{% url 'accounts:profile' article.user.username %}">{{ article.user }}</a>
    </p>
    <p>글 번호 : {{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <p>글 내용 : {{ article.content }}</p>
    <div>
      <form class="like-form" data-article-id="{{ article.pk }}">
        {% csrf_token %}
        {% if user in article.like_users.all %}
          <button id="like-button-{{ article.pk }}">좋아요 취소</button>
        {% else %}
          <button id="like-button-{{ article.pk }}">좋아요</button>
        {% endif %}
      </form>
      <p>
        <span id="like-count-{{ article.pk }}">{{ article.like_users.all|length }}</span>명이 이 글을 좋아합니다.
      </p>
    </div>
    <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
    <hr>
  {% endfor %}
{% endblock content %}

{% block script %}
<script>
  // 1. form 태그를 class 선택자로 선택
  const forms = document.querySelectorAll('.like-form')
  // console.log(forms)
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  // 2. for..of / forEach 여러 forms를 반복을 돌면서 axios를 요청할 수 있도록 함
  forms.forEach(form => {
    // console.log(form)
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      // console.log(event.target.dataset.articleId)
      const articleId = event.target.dataset.articleId

      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/articles/${articleId}/likes/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then(response => {
          // console.log(response.data)
          const liked = response.data.liked
          const likeButton = document.querySelector(`#like-button-${articleId}`)
          const likeCount = document.querySelector(`#like-count-${articleId}`)
          const count = response.data.count
          // const { liked, count } = response.data

          if (liked === true) {
            likeButton.innerText = '좋아요 취소'
          } else {
            likeButton.innerText = '좋아요'
          }

          // likeButton.innerText = liked ? '좋아요 취소' : '좋아요'

          likeCount.innerText = count
        })
    })
  })

</script>
{% endblock script %}

JS/0426_with django/댓글수정/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}